### ISSUE TITLE
Add Linux bake.sh and instructions

### ISSUE THREAD

**Issue by h3r2tic** [h3r2tic/cornell-mcray#1]
👀

**Comment by vshymanskyy** [comment]
Got it working on Ubuntu Linux + NVidia RTX3060
![image](https://user-images.githubusercontent.com/1506708/147234009-e11d6608-9ef9-43e3-a839-2d6af4d99272.png)

`libdxcompiler.so` was taken from https://github.com/microsoft/DirectXShaderCompiler#downloads

**Comment by h3r2tic** [comment]
Awesome! Happy to hear, and thank you for reporting 😀
