### ISSUE TITLE
Impossible to build because of `glam` conflicts

### ISSUE THREAD

**Issue by LoganDark** [h3r2tic/cornell-mcray#5]
This depends on an ancient version of `macaw` which re-exports an ancient version of `glam` that isn't compatible with any of the other `glam`s, upon upgrading that dependency suddenly `dolly` is also out of date, and trying to update `dolly` results in:

- dolly 0.3 has a too old version of glam.
- dolly 0.4.0 has a too new version of glam

so it's completely impossible to compile this project at all now, even with the Cargo.lock that's been committed.

Relying on types of `glam` for interoperability seems like a very, very bad idea with how unstable it seems to be

**Comment by h3r2tic** [comment]
I've just successfully build and ran it, but needed a matching `kajiya` version. Commit `4d813e330515922d92f26f09c2ff500e66aacd7d` should do the trick.

**Comment by LoganDark** [comment]
Aw, was hoping to benefit from `kajiya` improvements. Oh well.

That worked, thank you.

**Comment by h3r2tic** [comment]
There haven't been many updates in kajiya since, so you might be able to Frankenstein something, e.g. by cherry picking in kajiya, or strategically updating the deps 😅

**Comment by LoganDark** [comment]
Maybe! Also considered just fully updating kajiya and then taking cornell-mcray into my IDE.
